name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release. During the beta phase, we increment
    # the minor version number and set the patch number to 0.
    inputs:
      new-candidate-beta:
        type: choice
        required: true
        description: Select what kind of version bump this should be
        options:
          - minor
          - patch
      candidate-beta:
        required: true
        description: Release candidate version (beta, like 0.70.0)

      current-beta:
        required: true
        description: Current version (beta, like 0.69.1)
jobs:
  # Releasing opentelemetry-collector-contrib
  prepare-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "open-telemetry/opentelemetry-collector"
          path: opentelemetry-collector
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: opentelemetry-collector-contrib
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.7"
          cache: false

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          prefix: v
          workingDirectory: opentelemetry-collector-contrib

      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Outputs
        run: |
          echo "major: ${{ steps.semvers.outputs.major }}"
          echo "minor: ${{ steps.semvers.outputs.minor }}"
          echo "patch: ${{ steps.semvers.outputs.patch }}"
          echo "v_major: ${{ steps.semvers.outputs.v_major }}"
          echo "v_minor: ${{ steps.semvers.outputs.v_minor }}"
          echo "v_patch: ${{ steps.semvers.outputs.v_patch }}"

#      - name: Prepare release for contrib
#        working-directory: opentelemetry-collector-contrib
#        env:
#          GITHUB_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
#          REPO: open-telemetry/opentelemetry-collector-contrib
#          CANDIDATE_BETA: ${{ inputs.candidate-beta }}
#          CURRENT_BETA: ${{ inputs.current-beta }}
#        run: ./.github/workflows/scripts/release-prepare-release.sh
